# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi
import time
# initialize variables
mode = -1
    
def stop_others():
  global mode
  cyberpi.stop_other()
  cyberpi.led.off("all")
  cyberpi.console.clear()

@event.start
def on_start():
  global mode
  cyberpi.display.set_brush(255, 255, 255)
  cyberpi.display.show_label("Lighting Control", 12, "top_mid", index= 0)
  cyberpi.console.println("\nPress btn A: SOS")
  cyberpi.console.print("\nPress btn B: neon\n(multi-mode)")

@event.is_press('a')
def is_btn_press():
  global mode
  stop_others()
  mode = 0
  cyberpi.audio.set_vol(10)
  cyberpi.display.set_brush(255, 0, 0)
  cyberpi.console.clear()
  cyberpi.display.show_label("S O S", 32, "center", index= 0)
  cyberpi.display.show_label("...---...", 32, "bottom_mid", index= 1)
  while True:
    for count in range(3):
      cyberpi.audio.play_tone(700)
      cyberpi.led.on(255, 0, 0, "all")
      time.sleep(0.5)
      cyberpi.audio.stop()
      cyberpi.led.off("all")
      time.sleep(0.5)

    for count2 in range(3):
      cyberpi.audio.play_tone(700)
      cyberpi.led.on(255, 0, 0, "all")
      time.sleep(1.2)
      cyberpi.audio.stop()
      cyberpi.led.off("all")
      time.sleep(0.5)

    for count3 in range(3):
      cyberpi.audio.play_tone(700)
      cyberpi.led.on(255, 0, 0, "all")
      time.sleep(0.5)
      cyberpi.audio.stop()
      cyberpi.led.off("all")
      time.sleep(0.5)

    time.sleep(1)

@event.is_press('b')
def is_btn_press1():
  global mode
  if mode <= 0:
    mode = 1
    cyberpi.broadcast("step1")
  
@event.receive("step1")
def on_receive():
  global mode
  stop_others()
  cyberpi.broadcast("step2")

@event.is_press('up')
def is_joy_press():
  global mode
  if mode > 0:
    if mode == 7:
      mode = 1
    else:
      mode += 1
    cyberpi.broadcast("step1")

@event.is_press('down')
def is_joy_press1():
  global mode
  if mode > 0:
    if mode == 1:
      mode = 7
    else:
      mode -= 1
    cyberpi.broadcast("step1")
    
@event.receive("step2")
def on_receive2():
  global mode
  if mode == 1:
    mode_name = "Rainbow"
    cyberpi.display.set_brush(255, 255, 0)
    cyberpi.display.show_label(mode_name, 24, "top_mid", index= 0)
    cyberpi.console.println("\n\n\n\nJoystick up↑/down↓")
    while True:
      RainbowX()
  elif mode == 2:
    mode_name = "Spoondrift"
    cyberpi.display.set_brush(125, 125, 255)
    cyberpi.display.show_label(mode_name, 24, "top_mid", index= 0)
    cyberpi.console.println("\n\n\n\nJoystick up↑/down↓")
    while True:
      cyberpi.led.play('spoondrift')
  elif mode == 3:
    mode_name = "Meteor Blue"
    cyberpi.display.set_brush(20, 20, 200)
    cyberpi.display.show_label(mode_name, 24, "top_mid", index= 0)
    cyberpi.console.println("\n\n\n\nJoystick up↑/down↓")
    while True:
      cyberpi.led.play('meteor_blue')
  elif mode == 4:
    mode_name = "Meteor Green"
    cyberpi.display.set_brush(0, 255, 0)
    cyberpi.display.show_label(mode_name, 24, "top_mid", index= 0)
    cyberpi.console.println("\n\n\n\nJoystick up↑/down↓")
    while True:
      cyberpi.led.play('meteor_green')
  elif mode == 5:
    mode_name = "Helium Flash (R)"
    cyberpi.display.set_brush(255, 50, 0)
    cyberpi.display.show_label(mode_name, 24, "top_mid", index= 0)
    cyberpi.console.println("\n\n\n\nJoystick up↑/down↓")
    while True:
      cyberpi.led.play('flash_red')
  elif mode == 6:
    mode_name = "Helium Flash (O)"
    cyberpi.display.set_brush(200, 125, 0)
    cyberpi.display.show_label(mode_name, 24, "top_mid", index= 0)
    cyberpi.console.println("\n\n\n\nJoystick up↑/down↓")
    while True:
      cyberpi.led.play('flash_orange')
  else:
    mode_name = "Firefly"
    cyberpi.display.set_brush(0, 180, 0)
    cyberpi.display.show_label(mode_name, 24, "top_mid", index= 0)
    cyberpi.console.println("\n\n\n\nJoystick up↑/down↓")
    while True:
      cyberpi.led.play('firefly')
  
def RainbowX():
  c = {
    0: {'r': 255, 'g': 0, 'b': 0},
    1: {'r': 255, 'g': 32, 'b': 0},
    2: {'r': 255, 'g': 84, 'b': 0},
    3: {'r': 255, 'g': 126, 'b': 0},
    4: {'r': 255, 'g': 168, 'b': 0},
    5: {'r': 255, 'g': 210, 'b': 0},
    6: {'r': 255, 'g': 255, 'b': 0},
    7: {'r': 173, 'g': 255, 'b': 0},
    8: {'r': 0, 'g': 255, 'b': 0},
    9: {'r': 0, 'g': 255, 'b': 72},
    10: {'r': 0, 'g': 250, 'b': 154},
    11: {'r': 0, 'g': 255, 'b': 255},
    12: {'r': 0, 'g': 64, 'b': 192},
    13: {'r': 0, 'g': 0, 'b': 255},
    14: {'r': 64, 'g': 0, 'b': 255},
    15: {'r': 128, 'g': 0, 'b': 200},
    16: {'r': 192, 'g': 0, 'b': 120},
    17: {'r': 235, 'g': 0, 'b': 20},
  }
  l = len(c)
  for i in range(l):
    for j in range(5):
      n = (i+j)%l
      cyberpi.led.on(c[n]['r'], c[n]['g'], c[n]['b'], j+1)
    time.sleep(0.1)